name: ohlc_to_feature_store
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic to read data from
    defaultValue: ohlc_topic
    required: true
  - name: HOPSWORKS_PROJECT_NAME
    inputType: Secret
    description: ''
    defaultValue: HOPSWORKS_PROJECT_NAME
    required: true
  - name: HOPSWORKS_API_KEY
    inputType: Secret
    description: ''
    defaultValue: HOPSWORKS_API_KEY
    required: true
dockerfile: Dockerfile
runEntryPoint: main.py
defaultFile: main.py
